name = input('enter your name: ')
lastname = input('enter your lastname: ')
age = int(input('enter your age: '))
city = input('enter your city: ')
info = (name, lastname, age, city)
list =[]
# list.append(name)
# list.append(lastname)
# list.append(age)
# list.append(city)
list.append(info)
print(list)
print(list[0:2])
print(list[1:3])
print(list[0:3])
print(list[1:4])

